### PR TITLE
Recreate Suggestions Page

### PR DESCRIPTION
**Pull request by Mahak008**
Here is the screenshot of the changes made. Kindly letme know if you want anything else to be added or any other things required to get my PR merged.
Screenshot (333)

### CODE REVIEW

**Comment by Mahak008** [comment]
I am sorry, I closed this request by mistake. Kindly reconsider it @Kashishjain04 .

**Comment by Kashish1904** [comment]
I think you should add a litter border-radius to the container. Rest everything is perfect.
Add that radius, then I will merge this PR.

**Comment by Mahak008** [comment]
Hi, @Kashishjain04 
Thanks a lot for your suggestion. Actually, I accidentally deleted the forked repo due to which I am not getting the option to edit this file. If you know how this problem could be resolved, please let me know, I will surely make the changes. Else if possible kindly merge my PR.

**Comment by Kashish1904** [comment]
Ok no problem.
I am merging this repo as it is.

**Comment by Kashish1904** [comment]
Thans for your contribution.

**Comment by Kashish1904** [comment]
#5

**Comment by Mahak008** [comment]
> Thans for your contribution.

Thanks a lot for your support @Kashishjain04

**Pull request merged**
